version: '3'

services: 
  discovery-eureka-server:
    image: pl.braintelligence/discovery-eureka-server:latest
    ports:
      - 8761:8761
  
  centralized-configuration-server:
    image: pl.braintelligence/centralized-configuration-server:latest
    ports:
      - 8888:8888

  online-store-backend:
    image: pl.braintelligence/online-store-backend:latest
    ports:
      - 8080:8080
    depends_on: 
      - discovery-eureka-server
