eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-eureka-server:8761/eureka/

spring:
  application:
    name: "discovery-eureka-server"
