---
# class-path configuration example
server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          search-paths:
            - 'config*'


---
# git-based configuration example
server:
  port: 8888

spring:
  profiles:
    active: github
  cloud:
    config:
      server:
        git:
          uri: https://github.com/braintelligencePL/online-store-config
          search-paths:
            - 'config*'
